config/routes.rb
RoleManagement::Application.routes.draw do 

  get "welcome/index"

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :users,:except=>[:show]

    resources :admins,:only=>[:index]
    resources :managers,:only=>[:index]
    resources :customers,:only=>[:index]
    resources :photos,:only=>[:index,:create]

   root :to => 'welcome#index'

end

app/models/admin.rb
class Admin < User
	# Here we can customize base on this role and requirment
end

app/models/customer.rb
class Customer < User
	# Here we can customize base on this role and requirment
end

app/models/manager.rb
class Manager < User
	# Here we can customize base on this role and requirment
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:first_name,:last_name,:date_of_birth,:status,:type
  # attr_accessible :title, :body

  def to_s
  	first_name.to_s+" "+last_name.to_s
  end

  def active?
  	status?
  end

  def admin?
  	type=='Admin'
  end

  def manager?
  	type=='Manager'  	
  end

  def customer?
  	type=='Customer'
  end
  #Check if user is active before allowing user to sign in with devise
  def active_for_authentication?
    super && self.active?
  end

  def inactive_message
    "Sorry, this account has been deactivated."
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!    
  
  def autherize_admin?
  	unless current_user.admin?
  		flash[:error] = 'You are not authorized to access this page.'
  		redirect_to root_url
  	end  	
  end

  def autherize_manager?
  	unless current_user.manager?
  		flash[:error] = 'You are not authorized to access this page.'
  		redirect_to root_url
  	end  	
  end

  def autherize_customer?
  	unless current_user.customer?
  		flash[:error] = 'You are not authorized to access this page.'
  		redirect_to root_url
  	end  	
  end

  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  def after_sign_in_path_for(resource)  	
    case resource.type
    when 'Admin'
    	admins_url
    when 'Manager'
    	managers_url
    when 'Customer'    	
    	customers_url
    else
    	root_url
    end    
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter	:autherize_customer?
  def index
  end
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_filter :autherize_manager?
  def index
  end
end

app/controllers/photos_controller.rb
require "picasa"
class PhotosController < ApplicationController
	before_filter :establish_connection
  def index
  	begin
		  albums = @client.album.list.entries
		  album = albums.first#find { |album| album.title == "New Album" }

		  @photos = @client.album.show(album.id).entries		  
		rescue Exception => e
		  flash[:error] = "Some thing goes wrong from Picasa. Please try later."
	  	redirect_to root_url
		end		
  end  

  def create
  	begin
  	file_data = params[:image]		
	  photo_bin = file_data.read
	  albums = @client.album.list.entries
	  album = albums.first#find { |album| album.title == "New Album" }

	  @client.photo.create(album.id,
	    {
	      :binary => photo_bin,
	      :content_type => "image/jpeg",
	      :title => params[:title].present? ? params[:title] : "Test Photo",
	      :summary => params[:summary].present? ? params[:summary] : "Test Summary"
	    }
	  )
	  redirect_to photos_url
	rescue Picasa::ForbiddenError
	  flash[:error] = "Some thing goes wrong from Picasa. Please try later."
	  redirect_to root_url
	end
  end

  private

  def establish_connection
  	@client = Picasa::Client.new(:user_id => "hellofriends789@gmail.com", :password => "hellofriends789")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :autherize_admin?
	def index
		@users = User.order("created_at DESC")
	end

	def new
		type = case params[:type]
		when 'Admin'
			'Admin'
		when 'Manager'
			'Manager'
		else			
			'Customer'
		end
		@user = User.new(:type=>type)
	end

	def create		
		@user = User.new(params[:user])
		if @user.save
        redirect_to users_path, :notice => "#{@user.type} was successfully created."
	    else
	        render :action => "new"
	    end				
	end

	def edit
		@user = User.find params[:id]		
	end

	def update			
		@user = User.find(params[:id])		
	    if @user.update_attributes(params[:user])
	       redirect_to users_path, :notice => "#{@user.type} was successfully updated."
	    else
	      render :action => "edit"
	    end
	end

	def destroy
		@user = User.find(params[:id])		
		@user.destroy		
		redirect_to users_path, :notice => "#{@user.type} was successfully removed."
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!, :only => :index
  def index
  	if current_user
  		case current_user.type
	    when 'Admin'
	    	redirect_to admins_url
	    when 'Manager'
	    	redirect_to managers_url
	    when 'Customer'    	
	    	redirect_to customers_url
	    else	    	
	    end
  	end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/index.html.erb
<%= link_to "Photos", photos_path,:class => "btn btn-primary backCls" %>
<%= link_to "users", users_path ,:class => "btn btn-primary backCls"%>
<h1 class= "navbar-text">Admin Dashboard</h1></br>
<p>Here displays admin related information.</p>

app/views/customers/index.html.erb
<%= link_to "Photos", photos_path,:class => "btn btn-primary backCls" %>

<h1 class= "navbar-text">Customer Dashboard</h1>
<p>Here displays customer related information.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoleManagement</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-inner">
          <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
            <div class="nav-collapse">
              <ul class="nav">
        	     <li><%= link_to "Role Management", "/" %></li>
        	     <% if user_signed_in? %>
        	    	<li><a href="#">Signed in as <%= current_user.email %>. Not you?</a></li>
        	    	<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        	  	  <% else %>
        	    	<li><%= link_to "Sign In", new_user_session_path %></li>
                <li><%= link_to "Sign Up",new_user_registration_path %></li>
        	  	<% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <div class="span12"><%= yield %></div>
      </div>
</div>
</body>
</html>

app/views/managers/index.html.erb
<%= link_to "Photos", photos_path,:class => "btn btn-primary backCls" %>

<h1 class= "navbar-text">Manager Dashboard</h1>
<p>Here displays manager related information.</p>

app/views/photos/index.html.erb
<%= link_to "Back",:back, :class => "btn btn-danger backCls" %>
<h3 class= "navbar-text">Photos In Picasa</h3>
<fieldset>
	<legend>Upload Photo</legend>
	<%= form_tag({:action => 'create'},:method=>:post, :multipart => true) do %>	
	<p><%= file_field_tag 'image' %></p>
	<p><%= submit_tag "Upload", :disable_with => 'Please wait...', :class => "btn btn-primary" %></p>
	<% end %>
</fieldset>
<fieldset>
<div id="picasa_photos">	
	<% if @photos.present? %>
		<% @photos.reverse.each do |photo| %>
			<p class="col-xs-3"> <%= image_tag photo.media.cover_photo_url ,:size => "500x250",:class=>"thumbnail"%></p>
		<% end %>
	<% end %>
</div>
</fieldset>

app/views/users/_form.html.erb
  <% if f.object.errors.any? %>  
  <div id="errorExplanation">  
    <h2><%= pluralize(f.object.errors.count, "error") %> prohibited this user from being saved:</h2>  
    <ul>  
    <% f.object.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>  
  <% end %>  
  <%= f.hidden_field :type,:value=>f.object.type || params[:type] %>

  <div class="field">
    <label><%= f.label :first_name %></label>
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <label><%= f.label :last_name %></label>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <label><%= f.label :email %></label>
    <%= f.email_field :email %>
  </div>


  <div class="field">
    <label><%= f.label :password %>    
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <label><%= f.label :password_confirmation %></label>
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <label><%= f.label :date_of_birth %></label>
    <%= f.text_field :date_of_birth %>
  </div>
  <div class="field">
    <label><%= f.label :status %></label>
    <%= f.select :status, options_for_select([['Active',1],['Block',0]]) %>
  </div>

app/views/users/edit.html.erb
<%= link_to "Back",admins_path, :class => "btn btn-danger backCls" %>
<h2><%= @user.type %>&nbsp;/&nbsp;<%= @user.new_record? ? 'Add' : 'Edit' %></h2>
<%= form_for @user,:as=>:user,:url=>user_path(@user),:method=>:put do |f| %>  
	<%= render partial: 'form',:locals=>{:f=>f} %>
	<div class="actions">
	<%= f.submit "Save",:class => "btn btn-primary" %>
	</div>	
<% end %>

app/views/users/index.html.erb
<%= link_to "Add Admin",new_user_path(:type => "Admin"), :class => "btn btn-danger" %>
<%= link_to "Add Manager",new_user_path(:type => "Manager"), :class => "btn btn-danger " %>
<%= link_to "Add Customer",new_user_path(:type => "Customer"), :class => "btn btn-danger " %>
<%= link_to "Back",admins_path, :class => "btn btn-danger backCls" %>
<h3></h3>
<% if @users.present? %>
	<table class="table table-striped">
  <thead>
    <tr>
	    <th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Type</th>
			<th>Date of Birth</th>
			<th>Status</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
			<tr>
				<td><%= user.first_name %></td>
				<td><%= user.last_name %></td>
				<td><%= link_to user.email ,edit_user_path(user) %></td>
				<td><%= user.type.to_s %></td>
				<td><%= user.date_of_birth %></td>
				<td><%= user.status? ? 'Active' : 'Blocked' %></td>
				<td><%= link_to 'Delete',user_path(user) ,:method=>'delete',:confirm=>'Are you sure want to remove this user?' %></td>
			</tr>
		<% end %>
  </tbody>
</table>
<% else %>
	<p>No records found.</p>
<% end %>

app/views/users/new.html.erb
<%= link_to "Back",users_path, :class => "btn btn-danger backCls" %>
<%= form_for @user,:as=>:user,:url=>{:controller=>"users",:action=>'create'},:method=>:post do |f| %>  
	<%= render partial: 'form',:locals=>{:f=>f} %>
	<div class="actions">
	<%= f.submit "Save",:class => "btn btn-primary" %>
	</div>	
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome Page</h1>